// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BacklightInfo { effects: Array<number> | null, get_config_enabled: boolean, set_config_enabled: boolean, save_config_enabled: boolean, }