// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EncoderPositionConfig { layer: number, encoder: number, clockwise: number, keycode: number, }