// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { XAPDeviceDTO } from "./XAPDeviceDTO";
import type { XAPSecureStatus } from "./XAPSecureStatus";

export type FrontendEvent = { device: XAPDeviceDTO, } | { id: string, } | { id: string, secure_status: XAPSecureStatus, } | { id: string, log: string, };