// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { XAPDeviceInfo } from "./XAPDeviceInfo";

export type FrontendEvent = { id: string, device: XAPDeviceInfo, } | { id: string, };