// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Matrix } from "./Matrix";

export interface KeymapInfo { matrix: Matrix, layer_count: number | null, get_keycode_enabled: boolean, get_encoder_keycode_enabled: boolean, }