// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface KeymapInfo { layer_count: number | null, get_keycode: boolean, get_encoder_keycode: boolean, }