// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface QMKBoardIdentifiers { vendor_id: number, product_id: number, product_version: number, qmk_identifier: number, }