// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QMKBoardIdentifiers } from "./QMKBoardIdentifiers";

export interface QMKInfo { version: string, board_ids: QMKBoardIdentifiers, manufacturer: string, product_name: string, config: string, hardware_id: string, jump_to_bootloader_enabled: boolean, eeprom_reset_enabled: boolean, }