// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RemapInfo { layer_count: number | null, set_keycode_enabled: boolean, set_encoder_keycode_enabled: boolean, }