// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RGBMatrixConfig { enable: number, mode: number, hue: number, sat: number, val: number, speed: number, flags: number, }