// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacklightInfo } from "./BacklightInfo";
import type { KeymapInfo } from "./KeymapInfo";
import type { QMKInfo } from "./QMKInfo";
import type { RGBLightInfo } from "./RGBLightInfo";
import type { RGBMatrixInfo } from "./RGBMatrixInfo";
import type { RemapInfo } from "./RemapInfo";
import type { XAPInfo } from "./XAPInfo";

export interface XAPDeviceInfo { xap: XAPInfo, qmk: QMKInfo, keymap: KeymapInfo | null, remap: RemapInfo | null, backlight: BacklightInfo | null, rgb_light: RGBLightInfo | null, rgb_matrix: RGBMatrixInfo | null, }