// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeymapInfo } from "./KeymapInfo";
import type { LightingInfo } from "./LightingInfo";
import type { QMKInfo } from "./QMKInfo";
import type { RemapInfo } from "./RemapInfo";
import type { XAPInfo } from "./XAPInfo";

export interface XAPDeviceInfo { xap: XAPInfo, qmk: QMKInfo, keymap: KeymapInfo | null, remap: RemapInfo | null, lighting: LightingInfo | null, }