// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface XAPInfo { version: string, secure_status: boolean, secure_unlock: boolean, secure_lock: boolean, }