// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface XAPInfo { version: string, secure_status_enabled: boolean, secure_unlock_enabled: boolean, secure_lock_enabled: boolean, }