// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface XAPKeyCode { code: number, key: string, group?: string, label?: string, aliases: Array<string>, }