// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacklightInfo } from "./BacklightInfo";
import type { RGBLightInfo } from "./RGBLightInfo";
import type { RGBMatrixInfo } from "./RGBMatrixInfo";

export interface LightingInfo { backlight: BacklightInfo | null, rgblight: RGBLightInfo | null, rgbmatrix: RGBMatrixInfo | null, }