// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { XAPDeviceInfo } from "./XAPDeviceInfo";
import type { XAPKeyInfo } from "./XAPKeyInfo";
import type { XAPSecureStatus } from "./XAPSecureStatus";

export interface XAPDevice { id: string, info: XAPDeviceInfo, key_info: Array<Array<Array<XAPKeyInfo | null>>>, secure_status: XAPSecureStatus, }