// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyPosition } from "./KeyPosition";
import type { XAPKeyCode } from "./XAPKeyCode";

export interface XAPKeyCodeConfig { code: XAPKeyCode, position: KeyPosition, }