@startuml
rectangle "QMK XAP UI" {
    rectangle Frontend {
        [Vue.js]
    }
    rectangle Backend {
        [Tauri]
        [XAP Client]
    }
    [Vue.js] <--> [Tauri]: JSON RPC **(1)**
}

[Tauri] <--> [XAP Client]
[XAP Client] <..> [XAP Device 1]: USB HID
[XAP Client] <..> [XAP Device 2]: USB HID **(2)**
@enduml
