// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

export const commands = {
    async xapVersionQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|xap_version_query', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async xapCapabilitiesQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|xap_capabilities_query', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async xapEnabledSubsystemQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|xap_enabled_subsystem_query', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async xapSecureStatus(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|xap_secure_status', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async xapSecureUnlock(id: string): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|xap_secure_unlock', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async xapSecureLock(id: string): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|xap_secure_lock', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkVersionQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_version_query', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkCapabilitiesQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_capabilities_query', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkBoardIdentifiers(
        id: string,
    ): Promise<
        __Result__<
            {
                vendor_id: number
                product_id: number
                product_version: number
                qmk_unique_identifier: number
            },
            'Todo'
        >
    > {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_board_identifiers', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkBoardManufacturer(id: string): Promise<__Result__<UTF8String, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_board_manufacturer', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkProductName(id: string): Promise<__Result__<UTF8String, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_product_name', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkConfigBlobLength(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_config_blob_length', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkConfigBlobChunk(
        id: string,
        arg: number,
    ): Promise<
        __Result__<
            [
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
                number,
            ],
            'Todo'
        >
    > {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_config_blob_chunk', { id, arg }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkJumpToBootloader(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_jump_to_bootloader', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkHardwareIdentifier(
        id: string,
    ): Promise<__Result__<[number, number, number, number], 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_hardware_identifier', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async qmkReinitializeEeprom(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|qmk_reinitialize_eeprom', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async keymapCapabilitiesQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|keymap_capabilities_query', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async keymapGetLayerCount(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|keymap_get_layer_count', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async keymapGetKeycode(
        id: string,
        arg: KeymapGetKeycodeRequestArg,
    ): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|keymap_get_keycode', { id, arg }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async keymapGetEncoderKeycode(
        id: string,
        arg: KeymapGetEncoderKeycodeRequestArg,
    ): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|keymap_get_encoder_keycode', {
                    id,
                    arg,
                }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async remappingCapabilitiesQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|remapping_capabilities_query', {
                    id,
                }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async remappingGetLayerCount(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|remapping_get_layer_count', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async remappingSetKeycode(
        id: string,
        arg: RemappingSetKeycodeRequestArg,
    ): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|remapping_set_keycode', { id, arg }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async remappingSetEncoderKeycode(
        id: string,
        arg: RemappingSetEncoderKeycodeRequestArg,
    ): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|remapping_set_encoder_keycode', {
                    id,
                    arg,
                }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async lightingCapabilitiesQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|lighting_capabilities_query', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async backlightCapabilitiesQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|backlight_capabilities_query', {
                    id,
                }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async backlightGetEnabledEffects(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|backlight_get_enabled_effects', {
                    id,
                }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async backlightGetConfig(
        id: string,
    ): Promise<__Result__<{ enable: number; mode: number; val: number }, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|backlight_get_config', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async backlightSetConfig(
        id: string,
        arg: BacklightSetConfigRequestArg,
    ): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|backlight_set_config', { id, arg }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async backlightSaveConfig(id: string): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|backlight_save_config', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgblightCapabilitiesQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgblight_capabilities_query', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgblightGetEnabledEffects(id: string): Promise<__Result__<bigint, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgblight_get_enabled_effects', {
                    id,
                }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgblightGetConfig(
        id: string,
    ): Promise<
        __Result__<
            { enable: number; mode: number; hue: number; sat: number; val: number; speed: number },
            'Todo'
        >
    > {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgblight_get_config', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgblightSetConfig(
        id: string,
        arg: RgblightSetConfigRequestArg,
    ): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgblight_set_config', { id, arg }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgblightSaveConfig(id: string): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgblight_save_config', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgbmatrixCapabilitiesQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgbmatrix_capabilities_query', {
                    id,
                }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgbmatrixGetEnabledEffects(id: string): Promise<__Result__<bigint, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgbmatrix_get_enabled_effects', {
                    id,
                }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgbmatrixGetConfig(
        id: string,
    ): Promise<
        __Result__<
            {
                enable: number
                mode: number
                hue: number
                sat: number
                val: number
                speed: number
                flags: number
            },
            'Todo'
        >
    > {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgbmatrix_get_config', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgbmatrixSetConfig(
        id: string,
        arg: RgbmatrixSetConfigRequestArg,
    ): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgbmatrix_set_config', { id, arg }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async rgbmatrixSaveConfig(id: string): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|rgbmatrix_save_config', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async audioCapabilitiesQuery(id: string): Promise<__Result__<number, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|audio_capabilities_query', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async audioGetConfig(
        id: string,
    ): Promise<__Result__<{ enable: number; clicky_enable: number }, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|audio_get_config', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async audioSetConfig(
        id: string,
        arg: AudioSetConfigRequestArg,
    ): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|audio_set_config', { id, arg }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
    async audioSaveConfig(id: string): Promise<__Result__<null, 'Todo'>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('plugin:tauri-specta|audio_save_config', { id }),
            }
        } catch (e) {
            if (e instanceof Error) throw e
            else return { status: 'error', error: e as any }
        }
    },
}

/** user-defined types **/

export type AudioSetConfigRequestArg = { enable: number; clicky_enable: number }
export type BacklightSetConfigRequestArg = { enable: number; mode: number; val: number }
export type KeymapGetEncoderKeycodeRequestArg = {
    layer: number
    encoder: number
    clockwise: number
}
export type KeymapGetKeycodeRequestArg = { layer: number; row: number; column: number }
export type RemappingSetEncoderKeycodeRequestArg = {
    layer: number
    encoder: number
    clockwise: number
    keycode: number
}
export type RemappingSetKeycodeRequestArg = {
    layer: number
    row: number
    column: number
    keycode: number
}
export type RgblightSetConfigRequestArg = {
    enable: number
    mode: number
    hue: number
    sat: number
    val: number
    speed: number
}
export type RgbmatrixSetConfigRequestArg = {
    enable: number
    mode: number
    hue: number
    sat: number
    val: number
    speed: number
    flags: number
}
export type UTF8String = string

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from '@tauri-apps/api'
import * as TAURI_API_EVENT from '@tauri-apps/api/event'
import { type WebviewWindowHandle as __WebviewWindowHandle__ } from '@tauri-apps/api/window'

type __EventObj__<T> = {
    listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>
    once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>
    emit: T extends null
        ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
        : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>
}

type __Result__<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E }

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
    return new Proxy(
        {} as unknown as {
            [K in keyof T]: __EventObj__<T[K]> & {
                (handle: __WebviewWindowHandle__): __EventObj__<T[K]>
            }
        },
        {
            get: (_, event) => {
                const name = mappings[event as keyof T]

                return new Proxy((() => {}) as any, {
                    apply: (_, __, [window]: [__WebviewWindowHandle__]) => ({
                        listen: (arg: any) => window.listen(name, arg),
                        once: (arg: any) => window.once(name, arg),
                        emit: (arg: any) => window.emit(name, arg),
                    }),
                    get: (_, command: keyof __EventObj__<any>) => {
                        switch (command) {
                            case 'listen':
                                return (arg: any) => TAURI_API_EVENT.listen(name, arg)
                            case 'once':
                                return (arg: any) => TAURI_API_EVENT.once(name, arg)
                            case 'emit':
                                return (arg: any) => TAURI_API_EVENT.emit(name, arg)
                        }
                    },
                })
            },
        },
    )
}
